# -*- coding: utf-8 -*-
"""Test03_Data_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YXGb1rzMOfn5stfJchH9-n6lO9h-oZA
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

df = pd.read_csv("Titanic-Dataset.csv")

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE")
print(df.shape)

print("\nCOLUMN NAMES")
print(df.columns)

print("\nDATA TYPES")
print(df.dtypes)

print("\nDATASET INFORMATION")
print(df.info())

print("\nSTATISTICAL SUMMARY")
print(df.describe())

target = "Survived"

print("\nTARGET VARIABLE:")
print(target)

print("\nMISSING VALUES")
print(df.isnull().sum())

df['Age'].fillna(df['Age'].median(), inplace=True)

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df['Fare'].fillna(df['Fare'].median(), inplace=True)

if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)

print("\nMISSING VALUES AFTER CLEANING")
print(df.isnull().sum())

print("\nDUPLICATE RECORDS")
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("\nSHAPE AFTER REMOVING DUPLICATES")
print(df.shape)

print("\nDATA TYPES BEFORE CONVERSION")
print(df.dtypes)

df['Pclass'] = df['Pclass'].astype('category')

print("\nDATA TYPES AFTER CONVERSION")
print(df.dtypes)

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[(df['Fare'] >= lower_limit) &
(df['Fare'] <= upper_limit)]

print("\nSHAPE AFTER OUTLIER REMOVAL")
print(df.shape)

df.drop(['PassengerId', 'Name', 'Ticket'],
axis=1,
inplace=True)

print("\nCOLUMNS AFTER DROPPING IRRELEVANT FEATURES")
print(df.columns)

df = pd.get_dummies(df,
columns=['Sex', 'Embarked'],
drop_first=True)

print("\nDATA AFTER ENCODING")
print(df.head())

df['Fare'] = np.log1p(df['Fare'])

print("\nSKEWNESS HANDLED USING LOG TRANSFORMATION")

X = df.drop('Survived', axis=1)

y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
X,
y,
test_size=0.2,
random_state=42
)

print("\nTRAINING DATA SHAPE")
print(X_train.shape)

print("\nTESTING DATA SHAPE")
print(X_test.shape)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

print("\nFEATURE SCALING COMPLETED")

lr = LogisticRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("\n==============================")
print("LOGISTIC REGRESSION")
print("==============================")

print("\nACCURACY SCORE")
print(accuracy_score(y_test, y_pred_lr))

print("\nCONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred_lr))

print("\nCLASSIFICATION REPORT")
print(classification_report(y_test, y_pred_lr))

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print("\n==============================")
print("KNN CLASSIFIER")
print("==============================")

print("\nACCURACY SCORE")
print(accuracy_score(y_test, y_pred_knn))

print("\nCONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred_knn))

print("\nCLASSIFICATION REPORT")
print(classification_report(y_test, y_pred_knn))

dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("\n==============================")
print("DECISION TREE")
print("==============================")

print("\nACCURACY SCORE")
print(accuracy_score(y_test, y_pred_dt))

print("\nCONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred_dt))

print("\nCLASSIFICATION REPORT")
print(classification_report(y_test, y_pred_dt))

results = pd.DataFrame({

'Model': [
    'Logistic Regression',
    'KNN',
    'Decision Tree'
],

'Accuracy': [

    accuracy_score(y_test, y_pred_lr),

    accuracy_score(y_test, y_pred_knn),

    accuracy_score(y_test, y_pred_dt)
]

})

print("\n==============================")
print("MODEL COMPARISON")
print("==============================")

print(results)

df.to_csv("Cleaned_Titanic_Dataset.csv",
index=False)

print("\nCLEANED DATASET SAVED SUCCESSFULLY")